# Intro to NumPy, SciPy, and Matplotlib

## Numpy

In [3]:
import numpy as np

### Comparison of Numpy Array and List

In [4]:
x = [2,3,4,6] #usual Python List
y = np.array(x) #numpy array

In [5]:
print(type(x),x)
print(type(y),y)

<class 'list'> [2, 3, 4, 6]
<class 'numpy.ndarray'> [2 3 4 6]


In [6]:
print(x[1:3])

[3, 4]


In [7]:
print(y[1:3])

[3 4]


In [8]:
print(x[[0,2]])

TypeError: list indices must be integers or slices, not list

In [9]:
print(y[y>3])

[4 6]


In [10]:
print(x * 5)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [11]:
print(y * 5)

[10 15 20 30]


In [12]:
print(x ** 2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
print(y ** 2)

[ 4  9 16 36]


In [14]:
matrix = [[1,2,4],[3,1,0]] #matrix here is a nested list
nd_array = np.array(matrix)

In [15]:
print(matrix[1][2])

0


In [16]:
print(nd_array[1, 2])

0


In [17]:
print(np.random.rand())

0.9036981425378937


In [18]:
print(np.random.randn())

-0.1215231975349504


In [19]:
print(np.random.randn(4))

[ 1.28738245  0.92021377 -0.98250366 -1.10397509]


In [20]:
print(np.random.randn(4,5))

[[ 0.71894158 -0.86808929  0.7318404   0.6595781   0.73923739]
 [-1.63684637 -0.93041122 -1.02090048 -0.21317726 -0.52480607]
 [ 0.18912452 -0.68788128  0.89579421 -0.88196017  1.04991105]
 [-0.24939098 -0.68798994 -0.74951432  0.65010263 -0.55027736]]


### range() Method in Python and arange() in Numpy

In [21]:
print(np.arange(0, 8, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]


In [22]:
list(range(0, 8, 1))

[0, 1, 2, 3, 4, 5, 6, 7]

In [23]:
%timeit np.arange(0, 10000)
%timeit range(0, 10000)

5.88 µs ± 91 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
126 ns ± 2.15 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


## SciPy

In [24]:
from scipy import optimize

In [25]:
def f(x):
    return (x[0] - 3.2) ** 2 + (x[1] - 0.1) ** 2 + 3

print(f([3.2, 0.1]))

3.0


In [26]:
x_min = optimize.minimize(f, [5, 5])
print(x_min)

      fun: 3.0000000000011435
 hess_inv: array([[ 0.94055055, -0.16183475],
       [-0.16183475,  0.55944947]])
      jac: array([-2.05636024e-06,  5.36441803e-07])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 3
     njev: 4
   status: 0
  success: True
        x: array([3.19999896, 0.10000026])


In [27]:
print(x_min.x)

[3.19999896 0.10000026]


In [28]:
from scipy import linalg

In [31]:
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

x = linalg.solve(a, b)
print(x)

[ 2. -2.  9.]


In [32]:
print(np.dot(a, x))

[ 2.  4. -1.]


In [ ]:
X = np.random.randn(4, 3)
U, D, V = linalg.svd(X)
print(U.shape, D)